platform :ios, '12.0'
inhibit_all_warnings!
use_frameworks!

target 'GVImageLoader_Example' do
  pod 'GVImageLoader', :path => '../'

  target 'GVImageLoader_Tests' do
    inherit! :search_paths

    
  end
end
